## Essential classes in the package

- Basic Classes: ``MiniChain, MiniEntry``: load minimal information from PDB.
- `Chain` and `Entry` include additional structured entity information

In [1]:
from bri import Chain, Entry, MiniChain, MiniEntry
import matplotlib
matplotlib.use('TkAgg')
from matplotlib import pyplot as plt
import pandas as pd

In [2]:
entry1 = MiniEntry('AF_AFA0A009IHW8F1')
entry1

AF_AFA0A009IHW8F1

In [3]:
print(entry1.chains)

[AF_AFA0A009IHW8F1-1-A-1-269]

In [4]:
entry1.invariant

,pdb_id,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),...,x(A),y(A),z(A),x(C),y(C),z(C),length(N),length(A),length(C),chain_length
0,AF_AFA0A009IHW8F1,1,A,1,M,1.48,-0.462,1.454,1.48,-0.0,...,0.0,0.0,0.0,-0.462,1.454,-0.0,NaN,1.480,1.526,269
1,AF_AFA0A009IHW8F1,1,A,2,S,1.476,-0.544,1.435,-0.912,0.402,...,-0.507,1.386,-0.038,-0.729,0.348,1.304,1.338,1.476,1.534,269
2,AF_AFA0A009IHW8F1,1,A,3,L,1.468,-0.573,1.43,-1.189,0.218,...,-0.665,1.309,-0.034,-0.094,0.632,1.402,1.337,1.469,1.541,269
3,AF_AFA0A009IHW8F1,1,A,4,E,1.469,-0.592,1.419,0.621,0.91,...,-0.419,1.406,0.087,0.291,0.785,-1.29,1.334,1.470,1.538,269
4,AF_AFA0A009IHW8F1,1,A,5,Q,1.47,-0.555,1.428,0.64,0.958,...,-0.42,1.408,-0.041,0.171,0.589,-1.403,1.338,1.470,1.531,269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,AF_AFA0A009IHW8F1,1,A,265,V,1.475,-0.576,1.419,0.569,0.869,...,-0.372,1.425,0.076,0.402,0.768,-1.263,1.341,1.475,1.532,269
265,AF_AFA0A009IHW8F1,1,A,266,I,1.471,-0.57,1.422,0.585,0.914,...,-0.539,1.352,0.215,0.304,0.929,-1.18,1.334,1.471,1.532,269
266,AF_AFA0A009IHW8F1,1,A,267,L,1.463,-0.589,1.418,0.572,0.888,...,-0.469,1.375,0.177,0.633,0.972,-1.006,1.332,1.464,1.535,269
267,AF_AFA0A009IHW8F1,1,A,268,N,1.468,-0.578,1.427,0.843,1.043,...,-0.389,1.408,0.151,-0.976,0.208,1.173,1.342,1.469,1.540,269
268,AF_AFA0A009IHW8F1,1,A,269,R,1.471,-0.57,1.409,0.5,0.856,...,-0.442,1.396,-0.138,-0.805,0.22,-1.27,1.336,1.471,1.520,269

In [ ]:
entry1.get_entry_invariant(angles=True)

,pdb_id,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),...,length(N),length(A),length(C),chain_length,angle(N),angle(A),angle(C),tau(NA),tau(AC),tau(CN)
0,AF_AFA0A009IHW8F1,1,A,1,M,1.48,-0.462,1.454,1.48,-0.0,...,NaN,1.480,1.526,269,NaN,107.63,119.53,NaN,129.96,178.89
1,AF_AFA0A009IHW8F1,1,A,2,S,1.476,-0.544,1.435,-0.912,0.402,...,1.338,1.476,1.534,269,122.24,110.76,117.88,-62.62,151.06,177.81
2,AF_AFA0A009IHW8F1,1,A,3,L,1.468,-0.573,1.43,-1.189,0.218,...,1.337,1.469,1.541,269,123.90,111.84,117.39,-51.87,-39.42,179.16
3,AF_AFA0A009IHW8F1,1,A,4,E,1.469,-0.592,1.419,0.621,0.91,...,1.334,1.470,1.538,269,123.59,112.65,118.47,-71.07,-35.32,174.33
4,AF_AFA0A009IHW8F1,1,A,5,Q,1.47,-0.555,1.428,0.64,0.958,...,1.338,1.470,1.531,269,122.35,111.24,117.52,-65.18,-40.29,176.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,AF_AFA0A009IHW8F1,1,A,265,V,1.475,-0.576,1.419,0.569,0.869,...,1.341,1.475,1.532,269,123.49,112.09,118.03,-67.76,-41.22,-172.70
265,AF_AFA0A009IHW8F1,1,A,266,I,1.471,-0.57,1.422,0.585,0.914,...,1.334,1.471,1.532,269,123.64,111.84,117.32,-78.69,-43.31,-176.38
266,AF_AFA0A009IHW8F1,1,A,267,L,1.463,-0.589,1.418,0.572,0.888,...,1.332,1.464,1.535,269,124.22,112.56,118.47,-88.80,-2.67,-173.15
267,AF_AFA0A009IHW8F1,1,A,268,N,1.468,-0.578,1.427,0.843,1.043,...,1.342,1.469,1.540,269,125.65,112.05,116.97,50.32,48.75,179.77
268,AF_AFA0A009IHW8F1,1,A,269,R,1.471,-0.57,1.409,0.5,0.856,...,1.336,1.471,1.520,269,123.97,112.03,NaN,-108.58,NaN,NaN

In [6]:
chain1=MiniChain("1HHO", 1, "A", 1, 141)
chain1

1HHO-1-A-1-141

In [7]:
chain1.invariant

,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),z(N),x(A),y(A),z(A),x(C),y(C),z(C),length(N),length(A),length(C),chain_length
0,1,A,1,V,1.484,-0.506,1.464,1.484,-0.0,-0.0,0.0,0.0,0.0,-0.506,1.464,0.0,NaN,1.484,1.549,141
1,1,A,2,L,1.492,-0.55,1.416,-0.141,0.663,1.161,-0.686,1.312,0.189,-1.511,-0.16,-0.028,1.344,1.493,1.520,141
2,1,A,3,S,1.439,-0.41,1.439,-0.627,0.269,-1.096,-0.36,1.36,-0.3,-1.433,0.143,0.404,1.291,1.438,1.496,141
3,1,A,4,P,1.457,-0.546,1.436,-1.266,0.252,-0.245,-0.554,1.341,0.133,0.441,0.644,1.324,1.314,1.457,1.537,141
4,1,A,5,A,1.452,-0.527,1.424,0.749,0.984,0.49,-0.603,1.32,0.048,0.431,0.82,-1.202,1.330,1.452,1.518,141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,1,A,137,T,1.479,-0.59,1.425,0.848,1.018,-0.031,-0.457,1.403,-0.103,0.547,0.709,-1.256,1.325,1.479,1.543,141
137,1,A,138,S,1.457,-0.507,1.441,0.841,0.993,-0.242,-0.292,1.413,0.201,-0.614,0.577,-1.275,1.324,1.457,1.528,141
138,1,A,139,K,1.474,-0.52,1.448,0.909,0.965,0.102,-0.638,1.282,-0.348,0.189,0.285,-1.5,1.330,1.474,1.538,141
139,1,A,140,Y,1.533,-0.656,1.396,0.908,0.976,0.041,-0.454,1.381,-0.487,-0.092,0.158,-1.532,1.334,1.533,1.543,141
140,1,A,141,R,1.468,-0.503,1.447,0.788,0.999,0.345,-0.349,1.405,0.241,0.396,0.833,-1.222,1.318,1.468,1.531,141

In [8]:
chain1.get_chain_invariant(angles=True)

,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),z(N),...,length(N),length(A),length(C),chain_length,angle(N),angle(A),angle(C),tau(NA),tau(AC),tau(CN)
0,1,A,1,V,1.484,-0.506,1.464,1.484,-0.0,-0.0,...,NaN,1.484,1.549,141,NaN,109.07,120.02,NaN,-85.90,-168.85
1,1,A,2,L,1.492,-0.55,1.416,-0.141,0.663,1.161,...,1.344,1.493,1.520,141,126.23,111.23,111.72,76.34,113.96,-167.75
2,1,A,3,S,1.439,-0.41,1.439,-0.627,0.269,-1.096,...,1.291,1.438,1.496,141,119.71,105.90,116.65,-98.27,167.96,172.37
3,1,A,4,P,1.457,-0.546,1.436,-1.266,0.252,-0.245,...,1.314,1.457,1.537,141,121.73,110.82,119.43,-46.87,-25.02,-176.31
4,1,A,5,A,1.452,-0.527,1.424,0.749,0.984,0.49,...,1.330,1.452,1.518,141,116.80,110.31,116.18,-97.65,-23.60,176.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,1,A,137,T,1.479,-0.59,1.425,0.848,1.018,-0.031,...,1.325,1.479,1.543,141,122.18,112.49,116.75,-120.35,11.81,-167.78
137,1,A,138,S,1.457,-0.507,1.441,0.841,0.993,-0.242,...,1.324,1.457,1.528,141,125.11,109.38,117.24,-89.24,-4.95,166.28
138,1,A,139,K,1.474,-0.52,1.448,0.909,0.965,0.102,...,1.330,1.474,1.538,141,108.50,109.75,117.30,-92.33,-1.98,159.14
139,1,A,140,Y,1.533,-0.656,1.396,0.908,0.976,0.041,...,1.334,1.533,1.543,141,116.60,115.17,115.57,-76.66,-16.86,-172.52
140,1,A,141,R,1.468,-0.503,1.447,0.788,0.999,0.345,...,1.318,1.468,1.531,141,128.78,109.17,NaN,-101.95,NaN,NaN

In [9]:
entry2 = Entry('2hhb')
entry2.entity_info

{1: {'entity_poly_type': 'polypeptide(L)',
  'chain_id': 'A,C',
  'chain_length': 141,
  'pdbx_description': None},
 2: {'entity_poly_type': 'polypeptide(L)',
  'chain_id': 'B,D',
  'chain_length': 146,
  'pdbx_description': None}}

In [10]:
print(entry2.chains)
print(type(entry2['2HHB-1-1-A-1-141']))

[2HHB-1-1-A-1-141, 2HHB-2-1-B-1-146, 2HHB-1-1-C-1-141, 2HHB-2-1-D-1-146]
<class 'bri.pdbx2df.Chain'>

In [11]:
# BRI of an Entry object is the same to MiniEntry's
entry2.invariant

,pdb_id,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),...,x(A),y(A),z(A),x(C),y(C),z(C),length(N),length(A),length(C),chain_length
0,2HHB,1,A,1,V,1.447,-0.542,1.442,1.447,0.0,...,0.0,0.0,0.0,-0.542,1.442,-0.0,NaN,1.447,1.540,141
1,2HHB,1,A,2,L,1.469,-0.503,1.469,-0.914,0.246,...,-0.64,1.322,0.018,-1.101,0.011,1.095,1.305,1.469,1.553,141
2,2HHB,1,A,3,S,1.469,-0.477,1.451,-0.768,0.355,...,-0.658,1.312,-0.045,-1.105,0.016,1.055,1.295,1.468,1.528,141
3,2HHB,1,A,4,P,1.48,-0.54,1.415,-1.274,0.259,...,-0.539,1.379,-0.012,0.078,0.623,1.378,1.336,1.481,1.514,141
4,2HHB,1,A,5,A,1.449,-0.488,1.472,0.748,0.874,...,-0.38,1.398,0.031,0.139,0.575,-1.433,1.351,1.449,1.550,141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
569,2HHB,1,D,142,A,1.457,-0.612,1.395,0.76,0.977,...,-0.478,1.376,0.036,0.314,0.79,-1.264,1.323,1.457,1.523,146
570,2HHB,1,D,143,H,1.444,-0.611,1.402,0.834,1.025,...,-0.438,1.357,0.231,-0.819,0.582,-1.153,1.330,1.445,1.529,146
571,2HHB,1,D,144,K,1.474,-0.678,1.363,0.643,0.973,...,-0.59,1.349,0.059,0.529,1.015,-1.004,1.335,1.474,1.523,146
572,2HHB,1,D,145,Y,1.435,-0.493,1.443,0.761,1.017,...,-0.561,1.316,-0.117,-0.817,0.074,-1.286,1.319,1.435,1.525,146
573,2HHB,1,D,146,H,1.455,-0.576,1.424,-1.089,0.174,...,-0.678,1.277,-0.161,-1.496,-0.176,-0.301,1.314,1.455,1.536,146

## Extended use
These classes are intended to load minimal data for BRI computation. However, if there are any information interests you in the cif file, you can also add them into the object by customizing `extra_keys` parameter as `Dict[name_you_want, category_in_cif]`

In [12]:
entry_extra = Entry('2hhb', extra_keys={'true_database': 'database_2', 'false_database': 'database_not_in_cif'})
entry_extra

2HHB

In [13]:
entry_extra.true_database

[{'database_id': 'PDB',
  'database_code': '2HHB',
  'pdbx_database_accession': 'pdb_00002hhb',
  'pdbx_DOI': '10.2210/pdb2hhb/pdb'},
 {'database_id': 'WWPDB',
  'database_code': 'D_1000178190',
  'pdbx_database_accession': '?',
  'pdbx_DOI': '?'}]

In [14]:
# non-existing category gives nothing
entry_extra.false_database

- Set perturbation to atoms

In [15]:
chain1.perturb_radius = 0.1
chain1.invariant

,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),z(N),x(A),y(A),z(A),x(C),y(C),z(C),length(N),length(A),length(C),chain_length
0,1,A,1,V,1.45,-0.627,1.386,1.45,0.0,-0.0,0.0,0.0,0.0,-0.627,1.386,-0.0,NaN,1.450,1.521,141
1,1,A,2,L,1.543,-0.635,1.387,-0.073,0.584,1.183,-0.772,1.31,0.259,-1.518,-0.148,0.005,1.321,1.542,1.525,141
2,1,A,3,S,1.41,-0.382,1.481,-0.571,0.263,-1.128,-0.355,1.319,-0.348,-1.458,0.132,0.442,1.291,1.410,1.529,141
3,1,A,4,P,1.375,-0.648,1.38,-1.364,0.266,-0.317,-0.471,1.285,0.126,0.4,0.713,1.287,1.425,1.374,1.525,141
4,1,A,5,A,1.493,-0.504,1.417,0.811,1.051,0.457,-0.657,1.333,0.14,0.289,0.834,-1.218,1.404,1.493,1.504,141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,1,A,137,T,1.479,-0.628,1.384,0.858,1.009,-0.069,-0.342,1.433,-0.135,0.458,0.635,-1.302,1.326,1.479,1.519,141
137,1,A,138,S,1.5,-0.424,1.471,0.834,0.985,-0.207,-0.342,1.435,0.273,-0.556,0.56,-1.312,1.307,1.500,1.531,141
138,1,A,139,K,1.475,-0.547,1.491,0.897,0.944,0.096,-0.591,1.3,-0.368,0.082,0.213,-1.572,1.306,1.475,1.588,141
139,1,A,140,Y,1.547,-0.787,1.325,0.929,0.907,0.185,-0.412,1.426,-0.438,-0.105,0.364,-1.493,1.311,1.548,1.540,141
140,1,A,141,R,1.408,-0.64,1.363,0.832,1.01,0.479,-0.432,1.332,0.148,0.357,0.92,-1.138,1.393,1.408,1.506,141

In [16]:
chain1.perturb_radius = 0
chain1.invariant

,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),z(N),x(A),y(A),z(A),x(C),y(C),z(C),length(N),length(A),length(C),chain_length
0,1,A,1,V,1.484,-0.506,1.464,1.484,-0.0,-0.0,0.0,0.0,0.0,-0.506,1.464,0.0,NaN,1.484,1.549,141
1,1,A,2,L,1.492,-0.55,1.416,-0.141,0.663,1.161,-0.686,1.312,0.189,-1.511,-0.16,-0.028,1.344,1.493,1.520,141
2,1,A,3,S,1.439,-0.41,1.439,-0.627,0.269,-1.096,-0.36,1.36,-0.3,-1.433,0.143,0.404,1.291,1.438,1.496,141
3,1,A,4,P,1.457,-0.546,1.436,-1.266,0.252,-0.245,-0.554,1.341,0.133,0.441,0.644,1.324,1.314,1.457,1.537,141
4,1,A,5,A,1.452,-0.527,1.424,0.749,0.984,0.49,-0.603,1.32,0.048,0.431,0.82,-1.202,1.330,1.452,1.518,141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,1,A,137,T,1.479,-0.59,1.425,0.848,1.018,-0.031,-0.457,1.403,-0.103,0.547,0.709,-1.256,1.325,1.479,1.543,141
137,1,A,138,S,1.457,-0.507,1.441,0.841,0.993,-0.242,-0.292,1.413,0.201,-0.614,0.577,-1.275,1.324,1.457,1.528,141
138,1,A,139,K,1.474,-0.52,1.448,0.909,0.965,0.102,-0.638,1.282,-0.348,0.189,0.285,-1.5,1.330,1.474,1.538,141
139,1,A,140,Y,1.533,-0.656,1.396,0.908,0.976,0.041,-0.454,1.381,-0.487,-0.092,0.158,-1.532,1.334,1.533,1.543,141
140,1,A,141,R,1.468,-0.503,1.447,0.788,0.999,0.345,-0.349,1.405,0.241,0.396,0.833,-1.222,1.318,1.468,1.531,141

Set parameter `chain_length` longer than actual won't affect the actual data, but indeed impact the object's identifier

In [17]:
molchain = MiniChain('../tests/test_data/1ilz_extract.cif', 1, '.', 11, 2000)
print(molchain, 'gained', len(molchain), 'residues')
print(molchain.invariant)

1ILZ_EXTRACT-1-.-11-2000 gained 247 residues
    model_id chain_id residue_id residue_label  x(AN)  x(AC)  y(AC)   x(N)  \
0          1        .         11             L  1.459 -0.526  1.432  1.459
1          1        .         12             Q   1.46 -0.495  1.442  0.797
2          1        .         13             E  1.458 -0.584  1.418 -0.641
3          1        .         14             H   1.46 -0.516  1.435 -1.063
4          1        .         15             D  1.454 -0.526   1.43  -1.04
..       ...      ...        ...           ...    ...    ...    ...    ...
242        1        .        253             L  1.454 -0.475  1.448  -1.18
243        1        .        254             N   1.46 -0.535  1.426 -0.068
244        1        .        255             D  1.459 -0.415  1.472 -1.067
245        1        .        256             L  1.462 -0.592  1.406 -1.302
246        1        .        257             F  1.462 -0.515  1.432  0.747

      y(N)   z(N)   x(A)   y(A)   z(A)   x(C)   y(C)   z(C)  length(N)  \
0     -0.0    0.0    0.0    0.0    0.0 -0.526  1.432    0.0        NaN
1    0.918  0.541 -0.327  1.422 -0.032 -0.002  0.475 -1.449      1.331
2    0.412 -1.088 -0.462  1.379 -0.108 -1.278  0.253  0.809      1.328
3    0.183 -0.777 -0.671   1.29  -0.13 -1.278  0.004  0.832      1.329
4     0.27 -0.779 -0.537   1.35 -0.058 -0.779  0.311  1.272      1.327
..     ...    ...    ...    ...    ...    ...    ...    ...        ...
242  0.244 -0.551 -0.584  1.328  0.095  -0.94  0.021  1.199      1.325
243  0.599  1.183 -0.431  1.388  0.141  1.205  0.927  0.098      1.328
244  0.239 -0.758 -0.717  1.266   0.11 -1.222  -0.29  0.872      1.330
245  0.287  0.027  -0.43  1.394 -0.086  0.561  0.863  1.126      1.334
246   0.97  0.519 -0.394  1.403 -0.107   1.15  0.893  0.442      1.330

     length(A)  length(C)  chain_length
0        1.459      1.526           247
1        1.459      1.525           247
2        1.458      1.534           247
3        1.460      1.525           247
4        1.454      1.524           247
..         ...        ...           ...
242      1.454      1.524           247
243      1.460      1.523           247
244      1.459      1.529           247
245      1.461      1.526           247
246      1.461      1.522           247

[247 rows x 20 columns]

BIB and BID diagrams

In [18]:
molchain.generate_BIB().show()

In [19]:
molchain.generate_BID().show()

In [20]:
molchain.coordinates

,cate,residue_label,atom,chain_id,residue_id,x,y,z,occupancy,model_id
149,ATOM,LEU,N,.,11,7.726,8.634,-13.207,1.0,1
150,ATOM,LEU,CA,.,11,8.570,9.144,-14.282,1.0,1
151,ATOM,LEU,C,.,11,7.709,9.771,-15.374,1.0,1
152,ATOM,LEU,O,.,11,8.159,10.659,-16.098,1.0,1
153,ATOM,LEU,CB,.,11,9.425,8.015,-14.866,1.0,1
...,...,...,...,...,...,...,...,...,...,...
4053,ATOM,PHE,HD1,.,257,-3.168,-4.852,-8.486,1.0,1
4054,ATOM,PHE,HD2,.,257,-0.483,-5.621,-11.728,1.0,1
4055,ATOM,PHE,HE1,.,257,-3.730,-7.264,-8.368,1.0,1
4056,ATOM,PHE,HE2,.,257,-1.033,-8.037,-11.621,1.0,1
4057,ATOM,PHE,HZ,.,257,-2.659,-8.865,-9.939,1.0,1

In [21]:
molEntry = MiniEntry('../tests/test_data/AF-G5EB01-F1-model_v4.cif')
molEntry.invariant

,pdb_id,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),...,x(A),y(A),z(A),x(C),y(C),z(C),length(N),length(A),length(C),chain_length
0,AF-G5EB01-F1-MODEL_V4,1,A,1,M,1.471,-0.446,1.446,1.471,0.0,...,0.0,0.0,0.0,-0.446,1.446,0.0,NaN,1.471,1.513,217
1,AF-G5EB01-F1-MODEL_V4,1,A,2,D,1.468,-0.567,1.436,-0.865,0.399,...,-0.602,1.339,-0.018,-1.295,0.051,0.839,1.326,1.468,1.544,217
2,AF-G5EB01-F1-MODEL_V4,1,A,3,R,1.475,-0.548,1.425,-1.333,0.129,...,-0.69,1.299,-0.11,0.247,0.859,1.238,1.339,1.475,1.527,217
3,AF-G5EB01-F1-MODEL_V4,1,A,4,E,1.453,-0.539,1.437,0.633,0.873,...,-0.344,1.403,0.158,0.187,0.752,-1.324,1.323,1.453,1.534,217
4,AF-G5EB01-F1-MODEL_V4,1,A,5,Q,1.464,-0.578,1.421,0.604,0.898,...,-0.306,1.431,0.018,0.344,0.682,-1.331,1.335,1.463,1.535,217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,AF-G5EB01-F1-MODEL_V4,1,A,213,Y,1.455,-0.53,1.434,0.807,1.044,...,-0.459,1.37,0.17,0.93,0.965,-0.736,1.333,1.455,1.529,217
213,AF-G5EB01-F1-MODEL_V4,1,A,214,E,1.461,-0.477,1.457,-0.749,0.333,...,-0.683,1.276,-0.201,-1.458,-0.292,-0.374,1.330,1.461,1.533,217
214,AF-G5EB01-F1-MODEL_V4,1,A,215,V,1.466,-0.463,1.45,-1.002,0.307,...,-0.636,1.32,-0.037,-1.213,-0.045,0.919,1.333,1.466,1.522,217
215,AF-G5EB01-F1-MODEL_V4,1,A,216,I,1.465,-0.439,1.467,-0.781,0.376,...,-0.685,1.294,-0.062,-1.419,-0.228,0.528,1.332,1.465,1.531,217
216,AF-G5EB01-F1-MODEL_V4,1,A,217,E,1.473,-0.591,1.417,-0.702,0.414,...,-0.595,1.34,-0.138,-1.301,0.154,0.8,1.332,1.473,1.535,217

In [22]:
molEntry.perturb_radius = 0.1
molEntry.get_entry_invariant(angles=True)

,pdb_id,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),...,length(N),length(A),length(C),chain_length,angle(N),angle(A),angle(C),tau(NA),tau(AC),tau(CN)
0,AF-G5EB01-F1-MODEL_V4,1,A,1,M,1.417,-0.556,1.364,1.417,-0.0,...,NaN,1.417,1.473,217,NaN,112.18,116.91,NaN,125.03,177.21
1,AF-G5EB01-F1-MODEL_V4,1,A,2,D,1.512,-0.58,1.411,-0.868,0.304,...,1.346,1.513,1.525,217,120.56,112.35,119.22,-84.90,-176.12,-176.15
2,AF-G5EB01-F1-MODEL_V4,1,A,3,R,1.459,-0.487,1.372,-1.308,0.159,...,1.320,1.459,1.456,217,124.97,109.54,119.97,-69.39,-48.55,172.83
3,AF-G5EB01-F1-MODEL_V4,1,A,4,E,1.438,-0.633,1.321,0.48,0.852,...,1.286,1.437,1.465,217,130.71,115.60,117.65,-49.67,-45.99,174.30
4,AF-G5EB01-F1-MODEL_V4,1,A,5,Q,1.459,-0.62,1.401,0.463,0.894,...,1.306,1.460,1.531,217,127.84,113.87,115.03,-62.52,-40.59,178.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,AF-G5EB01-F1-MODEL_V4,1,A,213,Y,1.451,-0.491,1.46,0.865,0.957,...,1.329,1.452,1.540,217,118.16,108.59,109.93,-144.55,124.07,178.69
213,AF-G5EB01-F1-MODEL_V4,1,A,214,E,1.541,-0.523,1.591,-0.772,0.197,...,1.270,1.541,1.675,217,125.19,108.20,114.18,-131.46,131.76,173.70
214,AF-G5EB01-F1-MODEL_V4,1,A,215,V,1.429,-0.493,1.381,-0.919,0.26,...,1.303,1.429,1.466,217,120.47,109.65,116.33,-88.59,125.86,176.53
215,AF-G5EB01-F1-MODEL_V4,1,A,216,I,1.493,-0.373,1.559,-0.878,0.329,...,1.364,1.492,1.604,217,122.72,103.46,114.50,-102.47,111.84,172.15
216,AF-G5EB01-F1-MODEL_V4,1,A,217,E,1.502,-0.616,1.408,-0.568,0.433,...,1.334,1.502,1.537,217,121.16,113.63,NaN,-68.12,NaN,NaN

In [23]:
molEntry.entity_info

{1: {'entity_poly_type': 'polypeptide(L)',
  'chain_id': 'A',
  'chain_length': 217,
  'pdbx_description': None}}

In [24]:
molEntry2 = MiniEntry('../tests/test_data/AF-A0A0G3QJE1-F1-model_v4_sel80.0_extract.cif')
molEntry2.entity_info

{}

In [25]:
molEntry2.get_entry_invariant(angles=True)

,pdb_id,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),...,length(N),length(A),length(C),chain_length,angle(N),angle(A),angle(C),tau(NA),tau(AC),tau(CN)
0,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,1,M,1.484,-0.627,1.398,1.484,-0.0,...,NaN,1.484,1.532,291,NaN,114.16,121.55,NaN,-47.45,-176.41
1,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,2,R,1.488,-0.658,1.392,0.42,0.961,...,1.347,1.488,1.539,291,122.54,115.30,118.83,-68.79,-28.16,178.96
2,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,3,T,1.473,-0.583,1.414,0.656,1.021,...,1.333,1.474,1.529,291,123.43,112.41,118.66,-75.95,-43.48,179.18
3,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,4,F,1.474,-0.598,1.416,0.543,0.918,...,1.338,1.474,1.537,291,124.12,112.90,117.25,-61.14,-38.56,175.17
4,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,5,L,1.465,-0.57,1.431,0.619,0.927,...,1.339,1.464,1.540,291,122.83,111.72,118.42,-64.58,-34.96,177.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,287,L,1.467,-0.56,1.427,-1.143,0.25,...,1.334,1.467,1.533,291,123.36,111.43,116.68,-91.80,-54.28,179.00
287,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,288,N,1.462,-0.546,1.435,0.429,0.812,...,1.334,1.462,1.535,291,125.45,110.83,116.03,-127.22,140.00,174.12
288,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,289,D,1.466,-0.522,1.455,-1.063,0.22,...,1.330,1.466,1.546,291,124.40,109.74,118.66,-105.00,-166.63,-179.63
289,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,290,L,1.47,-0.643,1.4,-1.29,0.218,...,1.336,1.471,1.541,291,125.18,114.67,118.31,-59.88,-22.19,-176.57
290,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,291,F,1.467,-0.561,1.422,0.725,1.03,...,1.336,1.466,1.529,291,125.88,111.53,NaN,-114.35,NaN,NaN

In [26]:
molEntry2.perturb_radius = 0.5
molEntry2.invariant

,pdb_id,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),...,x(A),y(A),z(A),x(C),y(C),z(C),length(N),length(A),length(C),chain_length
0,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,1,M,1.157,-0.62,1.289,1.157,-0.0,...,0.0,0.0,0.0,-0.62,1.289,0.0,NaN,1.157,1.430,291
1,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,2,R,1.284,-0.579,1.809,-0.449,0.012,...,-0.818,0.929,0.339,1.016,1.565,0.359,1.936,1.283,1.900,291
2,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,3,T,1.61,-0.287,1.692,1.149,0.872,...,-0.597,1.495,0.037,-0.143,0.294,-1.685,1.443,1.610,1.716,291
3,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,4,F,1.266,-0.9,1.623,0.313,0.794,...,-0.074,1.263,-0.032,-0.044,0.857,-1.645,1.328,1.266,1.855,291
4,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,5,L,1.797,-0.743,1.219,0.595,0.283,...,-0.783,1.595,-0.267,0.404,0.856,-1.068,1.275,1.797,1.427,291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,287,L,1.511,-0.686,1.309,-1.174,0.432,...,-0.394,1.455,-0.102,-0.92,0.536,1.026,1.396,1.511,1.479,291
287,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,288,N,1.524,-1.246,1.19,0.415,0.783,...,-0.096,1.499,0.256,1.047,1.359,-0.151,1.442,1.524,1.722,291
288,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,289,D,1.429,-0.235,1.913,-0.61,-0.058,...,-0.595,1.29,0.156,-1.763,-0.611,0.484,0.778,1.429,1.928,291
289,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,290,L,1.675,0.051,2.064,-1.127,0.652,...,-0.334,1.589,-0.414,1.541,0.593,1.24,1.314,1.676,2.065,291
290,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,291,F,1.315,-0.606,1.435,0.673,0.641,...,-0.178,1.301,0.074,0.831,0.786,-1.056,1.324,1.315,1.557,291

In [27]:
molEntry2.perturb_radius = 0.0
molEntry2.invariant

,pdb_id,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),...,x(A),y(A),z(A),x(C),y(C),z(C),length(N),length(A),length(C),chain_length
0,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,1,M,1.484,-0.627,1.398,1.484,-0.0,...,0.0,0.0,0.0,-0.627,1.398,-0.0,NaN,1.484,1.532,291
1,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,2,R,1.488,-0.658,1.392,0.42,0.961,...,-0.644,1.339,0.073,0.206,0.897,-1.234,1.347,1.488,1.539,291
2,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,3,T,1.473,-0.583,1.414,0.656,1.021,...,-0.524,1.377,0.036,0.114,0.702,-1.354,1.333,1.474,1.529,291
3,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,4,F,1.474,-0.598,1.416,0.543,0.918,...,-0.454,1.4,0.084,0.139,0.754,-1.332,1.338,1.474,1.537,291
4,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,5,L,1.465,-0.57,1.431,0.619,0.927,...,-0.402,1.408,0.009,0.21,0.661,-1.375,1.339,1.464,1.540,291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,287,L,1.467,-0.56,1.427,-1.143,0.25,...,-0.661,1.31,0.011,-1.019,0.103,1.141,1.334,1.467,1.533,291
287,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,288,N,1.462,-0.546,1.435,0.429,0.812,...,-0.391,1.399,0.169,1.237,0.903,0.105,1.334,1.462,1.535,291
288,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,289,D,1.466,-0.522,1.455,-1.063,0.22,...,-0.743,1.263,-0.044,-1.338,-0.155,0.759,1.330,1.466,1.546,291
289,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,290,L,1.47,-0.643,1.4,-1.29,0.218,...,-0.648,1.32,0.031,0.593,0.984,1.027,1.336,1.471,1.541,291
290,AF-A0A0G3QJE1-F1-MODEL_V4_SEL80.0_EXTRACT,1,.,291,F,1.467,-0.561,1.422,0.725,1.03,...,-0.467,1.383,0.139,0.734,0.938,-0.958,1.336,1.466,1.529,291

- `MiniChain` has applied method `from_pdb` to load local PDB files
> NOTICE! Related functionalities are still under developing. As an `MiniChain` object should include data from one chain, trying to load .pdb files including multiple chains can cause unexpected results.

In [30]:
from bri.base.base_util import StructureBase
from bri import MiniChain
a = MiniChain.from_pdb('./example_input/1hho.pdb')
a.invariant

,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),z(N),x(A),y(A),z(A),x(C),y(C),z(C),length(N),length(A),length(C),chain_length
0,-1,A,1,V,1.484,-0.506,1.464,1.484,-0.0,0.0,0.0,0.0,0.0,-0.506,1.464,-0.0,NaN,1.484,1.549,287
1,-1,B,1,V,1.465,-0.636,1.401,32.78,6.994,17.837,-0.015,1.463,0.08,1.371,0.663,-0.215,37.968,1.465,1.538,287
2,-1,A,2,L,1.492,-0.55,1.416,8.99,-30.939,-21.954,-1.327,-0.682,-0.005,0.145,-1.484,-0.29,38.987,1.492,1.519,287
3,-1,B,2,H,1.432,-0.373,1.462,7.13,-37.25,-14.524,-0.438,-1.343,0.232,-1.356,-0.069,-0.66,40.612,1.432,1.510,287
4,-1,B,3,L,1.443,-0.451,1.448,0.295,0.482,1.19,-0.216,1.327,0.523,-1.494,0.262,-0.037,1.317,1.443,1.517,287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,-1,B,142,A,1.474,-0.504,1.445,-0.221,-31.492,-5.095,-0.646,1.08,-0.767,0.307,-0.185,-1.488,31.902,1.474,1.531,287
283,-1,B,143,H,1.447,-0.618,1.408,0.88,0.889,-0.297,-0.429,1.375,0.137,-0.757,0.536,-1.227,1.286,1.447,1.538,287
284,-1,B,144,K,1.459,-0.56,1.423,0.786,1.067,0.173,-0.705,1.276,-0.06,0.134,0.65,-1.378,1.336,1.459,1.529,287
285,-1,B,145,Y,1.493,-0.498,1.444,0.76,0.94,-0.551,-0.324,1.457,-0.036,-0.51,0.362,-1.393,1.328,1.493,1.527,287
286,-1,B,146,H,1.468,-0.599,1.415,1.015,0.838,0.007,0.041,1.463,0.107,0.297,0.69,-1.34,1.316,1.467,1.536,287

In [32]:
a.invariant

,model_id,chain_id,residue_id,residue_label,x(AN),x(AC),y(AC),x(N),y(N),z(N),x(A),y(A),z(A),x(C),y(C),z(C),length(N),length(A),length(C),chain_length
0,-1,A,1,V,1.484,-0.506,1.464,1.484,-0.0,0.0,0.0,0.0,0.0,-0.506,1.464,-0.0,NaN,1.484,1.549,287
1,-1,B,1,V,1.465,-0.636,1.401,32.78,6.994,17.837,-0.015,1.463,0.08,1.371,0.663,-0.215,37.968,1.465,1.538,287
2,-1,A,2,L,1.492,-0.55,1.416,8.99,-30.939,-21.954,-1.327,-0.682,-0.005,0.145,-1.484,-0.29,38.987,1.492,1.519,287
3,-1,B,2,H,1.432,-0.373,1.462,7.13,-37.25,-14.524,-0.438,-1.343,0.232,-1.356,-0.069,-0.66,40.612,1.432,1.510,287
4,-1,B,3,L,1.443,-0.451,1.448,0.295,0.482,1.19,-0.216,1.327,0.523,-1.494,0.262,-0.037,1.317,1.443,1.517,287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,-1,B,142,A,1.474,-0.504,1.445,-0.221,-31.492,-5.095,-0.646,1.08,-0.767,0.307,-0.185,-1.488,31.902,1.474,1.531,287
283,-1,B,143,H,1.447,-0.618,1.408,0.88,0.889,-0.297,-0.429,1.375,0.137,-0.757,0.536,-1.227,1.286,1.447,1.538,287
284,-1,B,144,K,1.459,-0.56,1.423,0.786,1.067,0.173,-0.705,1.276,-0.06,0.134,0.65,-1.378,1.336,1.459,1.529,287
285,-1,B,145,Y,1.493,-0.498,1.444,0.76,0.94,-0.551,-0.324,1.457,-0.036,-0.51,0.362,-1.393,1.328,1.493,1.527,287
286,-1,B,146,H,1.468,-0.599,1.415,1.015,0.838,0.007,0.041,1.463,0.107,0.297,0.69,-1.34,1.316,1.467,1.536,287